name: Shell Script Testing

on:
  pull_request:
    branches:
      - master
      - develop
      - test

  push:
    branches:
      - master
      - test
      - v1
      - v2

  workflow_dispatch:

jobs:
  Installer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Before Script
        run: |
          echo ${{ github.ref }}
          echo ${{ github.sha }}
          echo ${{ github.event_name }}

      - name: Update Package List
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt remove needrestart -y

      - name: Run Installer Script
        run: |
          echo "[+] Running the installer script..."
          sudo bash ./installer.sh

      - name: Run After Script
        run: |
          echo "[+] Running the after script..."
          sudo bash ./installer.sh

      - name: Run After Script Test
        run: |
          echo "[+] Running the after script..."
          bash ./installer.sh
