name: Shell Scripts Testing

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master
      - test

  workflow_dispatch:

jobs:
  Installer Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Before Script
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt -y remove needrestart

      - name: Run Installer Script
        run: |
          echo ${{ github.ref }}
          echo ${{ github.sha }}
          echo ${{ github.event_name }}
          echo "[+] Running the installer script..."
          sudo su 
          sudo bash ./installer.sh

      - name: Installer script result
        run: |
          echo "[+] Installer script result:"
          bash ./installer.sh
